/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.desktop.hideseek;

import com.desktop.hideseek.ui.MainFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        System.out.println(new App().getGreeting());
    }
}
